#spring:
#  datasource:
#    url: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#  flyway:
#    enabled: false
#
#app:
#  cookie:
#    domain: tiameds.ai
#
##AWS S3 Configuration
#aws:
#  s3:
#    access-key: ${env.AWS_ACCESS_KEY:${AWS_ACCESS_KEY:dummy}}
#    secret-key: ${env.AWS_SECRET_KEY:${AWS_SECRET_KEY:dummy}}
#    region: ${env.AWS_REGION:${AWS_REGION:ap-south-1}}
#    bucket-name: ${env.AWS_BUCKET_NAME:${AWS_BUCKET_NAME:dummy}}